### ISSUE TITLE
no utc/zulu indicator on date insert for get clients

### ISSUE THREAD

**Issue by mradamh** [botandrose/eboshi_api_shootout#31]
why are you not inserting zulu? https://github.com/botandrose/eboshi_api_shootout/blob/master/test/test.rb#L30-L31

`If no UTC relation information is given with a time representation, the time is assumed to be in local time. While it may be safe to assume local time when communicating in the same time zone, it is ambiguous when used in communicating across different time zones. Even within a single geographic time zone, some local times will be ambiguous if the region observes daylight saving time. It is usually preferable to indicate a time zone (zone designator) using the standard's notation.`

**Comment by botandrose** [comment]
Yeah it was originally there, but @ageoldpun's MySQL was shitting itself
trying to parse it. Which is weird, because it's the same version as mine
and Travis's. I blame Apple, because I have no other hypothesis. All the
tests still passed after removing the Z, and I couldn't figure out any
other way to get the UTC in the string, so I said fuck it. You running into
issues with lack of Z?

**Comment by mradamh** [comment]
yes, #32.  whatever is serializing dates in knex.js is assuming that is local time, which i don't think is necessarily wrong.

**Comment by botandrose** [comment]
Yeah, I was surprised that the tests still passed after removing it. I'll add the Z back, and Paul will be forced to troubleshoot his weird MySQL problem

**Comment by botandrose** [comment]
Closed by 3288e2a9. @ageoldpun FYI. My guess is configuration differences between default homebrew mysql and default debian mysql. We can compare.
